Repository websublime/schema, pull requests merged in 2022-02, with the labels that each got.

#2 feat: build process
  .changeset/README.md
  .changeset/config.json
  .changeset/unlucky-timers-pay.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/main-build.yml
  .github/workflows/publish-npm.yml
  LICENSE
  README.md
  package.json
  scripts/build.js
  src/constants/error-messages.constant.ts
  src/constants/schema-type.constant.ts
  src/index.ts
  src/models/error.model.ts
  src/schema-types/array.schema-type.ts
  src/schema-types/base.schema-type.ts
  src/schema-types/boolean.schema-type.ts
  src/schema-types/date.schema-type.ts
  src/schema-types/number.schema-type.ts
  src/schema-types/object.schema-type.ts
  src/schema-types/string.schema-type.ts
  src/schema.types.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, good first issue

#5 feat: add test coverage
  .prettierrc.json
  jest.config.js
  src/constants/error-messages.constant.ts
  src/models/error.model.ts
  src/schema-types/base.schema-type.ts
  src/schema-types/string.schema-type.ts
  tests/model/array-type.spec.ts
  tests/model/base-type.spec.ts
  tests/model/error-model.spec.ts
  tests/model/object-type.spec.ts
Labels: enhancement

#4 feat: readme file
  CONTRIBUTING.md
  LICENSE.md
  README.md
  black-logo.svg
  package.json
  white-logo.svg
Labels: documentation, enhancement

#6 feat: prepare script for publish release
  .changeset/grumpy-ears-marry.md
  .github/workflows/publish-npm.yml
  package.json
Labels: enhancement
